ivre/db/mongo.py, ivre/xmlnmap.py, web/cgi-bin/scanjson.py, web/static/help.js, web/static/ivre.js, web/static/templates/menu.html
This code uses the structured data from `smb-enum-shares.nse` Nmap script.
This requires a recent version of Nmap **and either** to reload the scans from the Nmap XML files **or** to use a script to adapt the results from your DB, like:
```python
def update_smb_enum_shares(archive=False):
cursor = ivre.db.db.nmap.get(
ivre.db.db.nmap.searchscript(name='smb-enum-shares', host=True),
fields=["_id", "scripts"],
archive=archive,
)
collection = ivre.db.db.nmap.colname_oldhosts if archive else ivre.db.db.nmap.colname_hosts
for host in cursor:
changed = False
for script in host['scripts']:
if script['id'] == 'smb-enum-shares' and 'smb-enum-shares' in script:
script['smb-enum-shares'] = ivre.xmlnmap.change_smb_enum_shares(script['smb-enum-shares'])
changed = True
if changed: …
```
=> Add functions to look for open SMB shares

ivre/db/mongo.py, web/cgi-bin/scanjson.py, web/static/help.js
Filter added to MongoDB specific code + WebUI.
This is a feature request from @serpilliere.
=> Add a filter to find hosts with at least one other open port than those specified 

ivre/xmlnmap.py, web/static/ivre.css, web/static/ivre.js, web/static/templates/view-hosts.html
This PR adds a basic support of CPE (Common Platform Enumeration) returned by some nmap components (osmatch, scripts or port information).
- `xmlnmap.py` now parses CPE information: any cpe is added to to the element that found it, for example:
```
[...]
ports: [
{
"service_method": "probed",
"state_reason": "syn-ack",
"state_reason_ttl": 119,
"protocol": "tcp",
"service_name": "msrpc",
"state_state": "open",
"cpes": [
"cpe:/o:microsoft:windows"
],
"service_product": "Microsoft Windows RPC",
"service_conf": 10,
"service_ostype": "Windows",
"port": 135
},
[...]
"osmatch": [
{
"line": "59470",
"cpes": [
"cpe:/o:microsoft:windows_7::-",
"cpe:/o:microsoft:windows_7::sp1",
"cpe:/o:microsoft:windows_server_2008::sp1",
"cpe:/o:microsoft:windows_8"
],
"name": "Microsoft Windows 7 SP0 - SP1, …
```
=> Parsing CPE (Common Platform Enumeration) strings

MANIFEST, doc/WEBUI.md, setup.py, web/dokuwiki/doc/webui.txt, web/static/help.js, web/static/index.html, web/static/ivre.js, web/static/templates/view-cpes-only.html
After PR #31, this adds a filter `display:cpe` to the Web UI to only display the CPE results.
=> WebUI: add display:cpe filter

bin/runscans
`optparse` module can be used when `argparse` is not available, but with `optparse` `nargs='+'` is not correct. The behavior will not be exactly the same, but if that's an issue, install `argparse`.
=> Fix runscans when argparse module is not available

bin/httpd-ivre, ivre/config.py, ivre/db/mongo.py, ivre/utils.py, tests/tests.py
A new method `.setscreenwords()` have been added to run `tesseract` against an already inserted screenshot.
The code calling `tesseract` has been moved from `ivre.db.mondo` (...) to `ivre.utils`.
A filter has been added when asking for `.topvalues("screenwords")` to make it faster.
=> "screenwords" improvements

web/static/ivre/graph.js
Worldmap has been broken since PR #50 (locations are no longer returned sorted by the number of IPs).
=> WebUI: fix worldmap

web/static/ivre/graph.js, web/static/ivre/utils.js
This PR (try to) enhances the responsiveness of top values graphs and chart maps, by:
* Removing arbitrary size (and using whole available space)
* Using background color for element inside histogram
* Render values in bold
Before:
After:
With another background and custom colors:
=> Responsive graph

.travis.yml
This prevent us from installing packages, but we can download tarballs instead, that we just extract and use.
=> Tests/TravisCI: switch to container based env

web/static/help.js
After that, filter `sshkey` will be similar to other filters with optional arguments (see #85).
=> WebUI/help: use homogeneous title for sshkey

setup.py
setup.py uses setuptools instead of distutils
setup for developers available:
```
python setup.py develop
```
=> setup.py now uses setuptools instead of distutils

web/static/help.js, web/static/ivre/tooltip.js
Fix #85 .
While typing `screenwor`, two commands are proposed: `screenwords` and `screenwords:`. Is it the wanted behavior?
=> Web: handle tooltip for command with parameters

web/static/ivre/ivre.css, web/static/templates/subview-port-summary.html, web/static/templates/subview-ports-summary.html, web/static/templates/subview-service-summary.html, web/static/templates/view-hosts.html
This PR aims to speed up the web rendering.
According to [Speeding up AngularJS apps with simple optimizations](https://www.binpress.com/tutorial/speeding-up-angular-js-with-simple-optimizations/135):
```
It’s known that Angular becomes slower with around 2,000 bindings due to the process behind dirty-checking. The less we can add to this limit the better, as bindings can add up without us really noticing it!
```
Using a `$$watchers` [counter](http://blog.yodersolutions.com/angularjs-count-the-number-of-watchers-on-a-page/), on a slow render query (`#1 range:64.170.144.217-69.39.229.61` on ModBus scan):
* Without the PR: 250 359 watchers (!)
* By rendering full view only if `host.fulldisplay`: 25494. On my computer, this is the difference between a "Slow script" box on Firefox and no box. …
=> Reactive web

bin/scancli, ivre/graphroute.py
This PR fixes `scancli` `graphroute`-related options and improves `graphroute`-related code.
It also adds support for clustering IP addresses in traceroute results, a la [Scapy](http://www.secdev.org/projects/scapy/doc/usage.html#tcp-traceroute-2).
=> Improve Graphroute code and possibilities

doc/WEBUI.md, ivre/db/__init__.py, ivre/db/mongo.py, ivre/webutils.py, ivre/xmlnmap.py, web/dokuwiki/doc/webui.txt, web/static/help.js, web/static/ivre/controllers.js, web/static/templates/menu.html
This PR contains code to use structured output generate by NSE script that use the "ls" module, and to generate it when importing results from Nmap without the "ls" module.
It is necessary to update existing host records by running `scancli --update-schema; scancli --update-schema --archives`.
Reference: [Nmap PR 106](https://github.com/nmap/nmap/pull/106) "Add an `ls` module to unify arguments and outputs for `-ls` scripts"
=> Handle Nmap's new "ls" NSE module

ivre/xmlnmap.py
Again, for the record, a Python script to update existing records:
```Python
import re
from ivre.db import db
for host in db.nmap.get(db.nmap.searchfile(re.compile(''),
scripts=['ftp-anon'])):
update = False
for port in host.get('ports', []):
for script in port.get('scripts', []):
if script['id'] == 'ftp-anon':
for fileentry in script['ls'].get(
'volumes', [{'files': []}])[0].get(
'files', []):
if isinstance(fileentry.get("size"), basestring) and fileentry['size'].isdigit():
fileentry["size"] = int(fileentry["size"])
print fileentry
update = True
if update:
db.nmap.db[db.nmap.colname_hosts].update(
{'_id': host['_id']},
{'$set': {
'ports': host['ports'],
}},
)
```
=> Nmap XML: fix ftp-anon file size type

docker/client/Dockerfile
Nmap version was fetched from a forked repository to use specific code (nmap/nmap#106)
that has been integrated into the Nmap dev tree.
Also, a workaround for nmap/nmap#34 has been added.
=> Docker/client: update Bro version + get "official" Nmap dev version

ivre/db/mongo.py
Some methods (screenshot-related) used `archives` instead.
=> DB/Mongo: always use `archive` as optional parameter

ivre/db/__init__.py
Until this, nmap2db would stop after merging the first already existing host.
=> nmap2db: fix --merge with JSON files

ivre/db/mongo.py
Stack trace :
$ runscans-agentdb --add-local-master
$ runscans-agentdb --add-agent ivre-share/fs/ --source MySource              
$ runscans-agentdb --list-agents
agent:
Traceback (most recent call last):
File "/usr/local/bin/runscans-agentdb", line 227, in <module>
main()
File "/usr/local/bin/runscans-agentdb", line 190, in main
display_agent(agent)
File "/usr/local/bin/runscans-agentdb", line 55, in display_agent
print "  - id: %s" % agent['_id']
File "/usr/lib/python2.7/dist-packages/pymongo/cursor.py", line 599, in __getitem__
"instances" % index)
TypeError: index '_id' cannot be applied to Cursor instances
=> Fix error when using --list-agents with runscans-agentdb

bin/analysercli, ivre/webutils.py
Without this PR, only filters with value are allowed in `analysercli`. That way, filters like `openport` are ignored and end with a CLI crash.
With this PR, filter handling is the same than for the web interface, allowing a more (in my opinion) convenient / usual way of specifying them.
```
$ ./analysercli 
[INFO] Initialization
Filter > openport category:Random limit:1000
[INFO] Reading database..
. > count
[INFO] Number of hosts:
total:	1000
```
=> Fix analysercli filter

MANIFEST, ivre/db/__init__.py, ivre/db/mongo.py, ivre/nmapout.py, ivre/tools/scan2db.py, ivre/tools/scancli.py, ivre/xmlnmap.py
This allows for users to get a "normal" Nmap output (as generated by `nmap -oN -`, or by `ivre scancli`) from XML (as generated by `nmap -oX -`) or JSON (as generated by `ivre scancli --json`) output without the need to import the result in IVRE's DB.
=> Command line: add --test-normal to scan2db

agent/agent
The agent now spawns worker agent subprocesses, waits for them while at
least one is alive, and kills (SIGTERM) its whole process tree on exit,
SIGINT or SIGTERM.
This allows to use the agent more flexibly (for example in a systemd
service). As a bonus, it removes the `screen` dependency on the agent side, for what it is worth... 
The PR also adds some light logging to see what the agent workers are doing. @pl, could you also check that these messages are consistent?
As a preview/bonux, here is a sample systemd service file I use to run the agent on by boxes:
```cfg
[Unit]
Description=IVRE scan agent
After=network.target
Requires=network.target
[Service]
EnvironmentFile=-/etc/sysconfig/ivre-agent
WorkingDirectory=/var/lib/ivre-agent/
ExecStartPre=/bin/sh -c 'mkdir -p input output' …
```
=> Replace screen by "proper" subprocess management in agent

ivre/db/mongo.py
The count() operation was slowing down huge file imports.
Replacing it with a find_one() reduces import time by 10.
This is particularly effective on huge files.
=> Replaced count() with find_one() in the remove() function

ivre/tools/runscansagent.py
This fixes `ivre runscansaent` used with neither `--sync` nor `--feed`.
=> CLI: fix runscansagent w/ screen

ivre/db/mongo.py, ivre/xmlnmap.py
This PR:
* Add error magics for [`mongodb-info`](https://nmap.org/nsedoc/scripts/mongodb-info.html), [`mongodb-databases`](https://nmap.org/nsedoc/scripts/mongodb-databases.html) NSE scripts.
* Parse `mongodb-databases` output, including databases and shards.
* Fix the order of execution of output error detection and output parsing.
=> Partial parsing of mongodb-{info,databases} NSE scripts

ivre/xmlnmap.py
A few `IGNORE_SCRIPTS` patterns were redundant with the one in `IGNORE_SCRIPT_OUTPUTS_REGEXP` and then useless.
=> XMLNmap: redundant ignore with IGNORE_SCRIPT_OUTPUTS_REGEXP

.travis.yml, ivre/db/mongo.py, ivre/tools/ipinfo.py, ivre/tools/scancli.py, tests/tests.py
This saves memory and is much more efficient.
Also, `ivre scancli` uses `.distinct()`, which fixes #274.
=> DB/Mongo: add .distinct() method using the aggregation framework

ivre/xmlnmap.py
I think this pull request is what was wanted to avoid parsing of unnecessary outputs while being able to keep screenshots imported and cleaned from their output as well.
=> Ignore some scripts output and keep HTTP screenshots (fix #288)

ivre/target.py
If we use --nmap-prescan-ports without the --nmap-prescan-opts option, target.py will try to split the opts string with shlex.split() which is an incorrect action.
=> Make --nmap-prescan-ports functionnal

ivre/db/mongo.py, ivre/tools/bro2db.py, ivre/utils.py, ivre/xmlnmap.py, web/cgi-bin/scanjson.py
This handles more services from Masscan, and matches the `banner` output against Nmap service fingerprint database (Nmap needs to be installed on the computer running `ivre scan2db`).
This PR also includes a minor fix and the ability to get top values for `product:service` (only `product:port_number` was supported).
=> Match banners from Masscan against Nmap service fingerprints

ivre/xmlnmap.py
- Don't display the "WARNING: File not found" if file has been successfully inserted to database
=> XML/Nmap: fix exception handling when adding screenshots to db

.travis.yml, doc/README.md, web/dokuwiki/doc/readme.txt
With this PR, we run the Travis-CI tests against two different MongoDB versions (2.6.10, which has to be supported per our documentation, and 3.4.2, the current latest stable release).
=> Test multiple MongoDB versions

ivre/agent.py
This is useful for target files with multiple hosts.
=> Agent: change "down" test from "one host down" to "all down"

.travis.yml, .travis/ivre.conf, ivre/agent.py, ivre/xmlnmap.py, nmap_scripts/http-screenshot.nse, tests/tests.py
This fixes a Python 3 issue with screenshot files. It adds tests, for this bug, for the `http-screenshot` Nmap script, and for the screenshots integration in IVRE (including the use of Tesseract to extract words from screenshots).
It also makes agents able to handle screenshots and adds a `geometry` argument in the `http-screenshot` script to control the browser's window size.
Fixes #408.
=> Fix and improve screenshots handling

doc/INSTALL.md, ivre/config.py, tests/tests.py
This PR allows to add a top priority configuration file by setting the environment variable `IVRE_CONF`.
=> Conf: allow setting a config file via env

ivre/passive.py, ivre/tools/passiverecon2db.py
This is the first step to allow putting other standard bro logs into db. The goal was to refactor the `ivre.passive` code to be *less* adherent to how passiverecon logs are structured.
=> Use BroFile to parse passiverecon logs

docker/client/Dockerfile
avoid ivre/utils.py:702 warning
=> feat(docker/client): install  python-pil needed by scan2db to trim_image 

docker/base/Dockerfile
=> Docker: install ca-certificates in base for ipdata download

nmap_scripts/http-screenshot.nse
=> Nmap scripts/http-screenshot: accept invalid SSL certificates

doc/DOCKER.md, docker/web-apache/Dockerfile, web/dokuwiki/doc/docker.txt
The documentation update is related to #483.
The build file (`Dockerfile`) has been fixed, and `ivre/web-apache` images should now be built automatically.
=> Docker: fix doc and build for web-apache

bro/ivre/passiverecon/__load__.bro
Namely: ignore gridftp-data & irc-dcc-data (ftp-data was already ignored)
=> Passivereon: ignore more TCP banners based on c$service

ivre/parser/bro.py, requirements-mongo-26.txt
This will make Bro parser work with different log formats (`cat old_format.log new_format.log | ivre passiverecon2db` would crash or bug without this patch).
The PR also includes a patch to fix PyMongo version for Python 2.6 (MongoDB / Python 2.6 tests were broken without this).
=> Bro: handle header lines after data lines

ivre/utils.py, tests/tests.py
Since "EU" is no longer a used country code in Maxmind GeoIP databases (since #530), this PR renames the previous "EU*" alias to "EU".
=> GeoIP: rename EU* alias to EU

ivre/target.py
=> Targets: use .__len__() as the target count can be more than sys.maxsize

setup.py, web/static/templates/subview-host-summary.html, web/static/templates/subview-port-summary.html
This PR fixes three minor things:
- The `view-ports-only.html` (used by the `displayPort` directive) and `view-services-only.html` (used by the `displayService` directive) files are missing from the `setup.py` file (since its creation).
- When an host doesn't have a name, some "OCD nagging" empty parentheses `()` are left behind in the rendered `subview-host-summary.html` template.
- Using `ng-src` instead of `src` allowing Angular to compile the template 
before the browser tries to download the screenshot (shown in the browser console as an error `GET data:image/jpeg;base64,{{::port.screendata}} net::ERR_INVALID_URL`)
=> WebUI: multiple fixes

ivre/passive.py
We enforce a `utils.MAXVALLEN // 10` size limits for subkey values in subject and issuer; this is because MongoDB cannot index values longer than 1024 bytes, and subject and issuer fields may have more than one key.
=> Passive: limit data size in subject and issuer of certificate records

ivre/db/mongo.py, ivre/db/sql/__init__.py, ivre/db/sql/postgres.py, ivre/db/sql/tables.py, ivre/keys.py, ivre/passive.py, ivre/tools/ipinfo.py, ivre/view.py
Move 'fullvalue' and 'fullinfos' functions in mongodb specific code, since they are used only for size restrictions on mongodb indexes.
=> Passive: hide full{value,infos} from user, move it to MongoDB specific code

ivre/xmlnmap.py
Since the sslv2-drown NSE script mixes elem/table tags with and without key attributes which is currently unsupported, the script needs to be ignored. This was causing the import of some hosts to fail.
=> Nmap: Ignore sslv2-drown NSE script

ivre/db/mongo.py
While calculating the top CPEs, I got the following error.
```
Traceback (most recent call last):
File "/usr/lib64/python3.7/wsgiref/handlers.py", line 138, in run
self.finish_response()
File "/usr/lib64/python3.7/wsgiref/handlers.py", line 179, in finish_response
for data in self.result:
File "/home/ivre/.env-ivre/lib/python3.7/site-packages/ivre/web/app.py", line 295, in get_nmap_top
topnbr=topnbr))
File "/home/ivre/.env-ivre/lib/python3.7/site-packages/ivre/db/mongo.py", line 2599, in topvalues
fields = fields[:max(fields.index(field), len(cpeflt)) + 1]
TypeError: object of type 'zip' has no len()
```
Python 3 no longer supports using the `len` built-in on `zip` objects. The best (?) option is to convert the `cpeflt` to a list before trying to calculate the length. Since the `cpeflt` …
=> DB/Mongo: Fix top CPE (object of type 'zip' has no len()")

.travis.yml, bro/ivre/passiverecon/bare.bro, bro/ivre/passiverecon/ja3.bro, doc/INSTALL.md, doc/README.md, web/dokuwiki/doc/install.txt, web/dokuwiki/doc/readme.txt
#624 made Ivre's "passiverecon" Bro script compatible with Bro 2.6 only. It was actually easier than I initially thought to continue to also support 2.5(.x).
This also adds Travis tests with random Bro versions (2.5 and 2.6).
=> Make Ivre's Bro script compatible with Bro 2.5 and 2.6

doc/INSTALL.md, requirements-neo4j.txt, requirements.txt, setup.py, web/dokuwiki/doc/install.txt
The API has changed in version 4, and we do not want to spend time to port IVRE's code to py2neo 4 for now.
Fixes #571.
=> DB/Neo4j: pin py2neo version to 3.*

bro/ivre/__load__.bro
SMB is enabled by default with Bro 2.6 and more.
=> Bro: enable SMB with Bro < 2.6

ivre/db/__init__.py, ivre/web/utils.py, tests/tests.py
This PR also fixes `DBView.searchja3server()` API to match `DBPassive.searchja3server()`.
=> DB/View: support regexp lookups in .searchja3*()

ivre/db/__init__.py, ivre/utils.py, ivre/view.py, ivre/web/utils.py, tests/results-public-samples, tests/tests.py, web/dokuwiki/doc/webui.txt, web/static/ivre/content.js
The option `http-user-agent` (cli and webui) accepts : 
- nothing : every hosts known to use a User-Agent will be retrieved.
- or a string : that will retrieve every hosts which use this exact User-Agent
- or a regular expression : that will retrieve every hosts which use a User-Agent that matches the regex
=> Import User-Agents from passive into view with corresponding filters

ivre/geoiputils.py, pkg/arch/PKGBUILD
This has been applied to [AUR](https://aur.archlinux.org/pkgbase/ivre/) and BlackArch (BlackArch/blackarch#2275), without the `ivre-data` package.
This package is specifically useful for offline networks.
=>  Split package into ivre, ivre-docs, ivre-web, python{,2}-ivre and ivre-data

nmap_scripts/http-screenshot.nse
Since NMap 7.70 string operations have been moved to stringaux.lua. This PR checks if stringaux is present, if not the old stdnse is used.
=> Handled stringaux and stdnse

.travis.yml, ivre/db/mongo.py, ivre/db/sql/__init__.py, ivre/tools/ipinfo.py
When `new` is set to `True` (which is now the default, so that existing calls without specifying a value for `new` will return the same results), the field used to filter record is `firstseen`. When it is `False`, the field used is `lastseen`.
=> Passive: fix .searchtimeago() and .searchnewer() new= parameter

web/static/doc/dev/web-api.html, web/static/ivre/content.js
As suggested by @trou in #740, this will make it clear that regular expressions should be specified using the `/regexp/` syntax.
=> Web: update doc

ivre/db/elastic.py
The current implementation is limited to "count" 10000 records by default.
=> DB/Elastic: fix .count()

ivre/db/mongo.py, ivre/db/neo4j.py, ivre/flow.py, ivre/tools/flowcli.py, tests/results-public-samples, tests/tests.py
`--fields` option without further argument prints the list of available fields. General fields have been hard coded (with a description of their meaning, I don't know if it's relevant...). Metadata fields are derived from already existing dictionaries.
General fields are meant to work with every backends, while metadata fields work only in MongoDB backend for now (and won't work with Neo4j). These fields can be used in filters, in field selector (`--fields` with arguments) and in topvalues.
Furthermore, fields used in filters, in `--fields` and in `topvalues` are now verified: you will get an error if you try to use an unavailable field. There are some special cases:
- `addr` field does not physically exist in databases. It is just a shortcut used in filters instead of `src.addr = X OR …
=> Flow: fields list and bugfixes in flowcli

ivre/utils.py
On a MacOS laptop, I still have an issue with the manuf file (accessible here: https://server.vruello.fr/manuf) despite #826.
The error is:
```
file "Projects/ivre/venv/bin/ivre", line 88, in <module>
main()
File "Projects/ivre/venv/bin/ivre", line 60, in main
tools.get_command(next(iter(possible_commands)))()
File "Projects/ivre/venv/lib/python2.7/site-packages/ivre/tools/view.py", line 191, in main
displayfunction(cursor)
File "Projects/ivre/venv/lib/python2.7/site-packages/ivre/tools/view.py", line 174, in displayfunction
displayhosts(cursor, out=sys.stdout)
File "Projects/ivre/venv/lib/python2.7/site-packages/ivre/nmapout.py", line 176, in displayhosts
displayhost(record, out=out, **kargs)
File "Projects/ivre/venv/lib/python2.7/site-packages/ivre/nmapout.py", line 138, in displayhost …
```
=> View: Fix errors when a malformed manuf file is used

ivre/tools/iphost.py
I suggest that unsuccessful DNS resolutions of type A/AAAA would be displayed with `ivre iphost domain.example`. For instance:
```
$ ivre iphost --sub example
domain.example A None (8.8.8.8, 1 time, 2020-02-01 12:00:00.000000 - 2020-02-01 12:00:00.000000)
```
instead of 
```
$ ivre iphost --sub example
WARNING:ivre:Cannot display record {...}
```
=> iphost: display unsuccessful A/AAAA resolutions

ivre/db/maxmind.py, ivre/tools/version.py, ivre/utils.py
Some quick fixes to allow Ivre to run on Windows:
- on Windows, os.uname() does not exists, use sys.platform (guaranteed to exist)
- a leading "/" prevent maxmind db extraction, strip it on Windows (there might be a better way to do it)
- Fix the alternate hashing method: .read return bytes therefore returns b"" and not ""
=> Fix Ivre on Windows

bin/ivre, ivre/tools/scan2db.py
This PR will catch (and ignore) broken pipe errors from all CLI tools, and properly warn the user in case of non existent file or directory in `ivre scan2db` (see #926).
=> Fix CLI errors

ivre/db/tiny.py, requirements-tinydb.txt, setup.py
Since msiemens/tinydb#313 has been fixed in release 4.1.0, IVRE can now support both TinyDB v3.x.x (for Python < 3.5) and TinyDB v4.x.x (for Python >= 3.5).
=> DB/TinyDB: support TinyDB v4

ivre/xmlnmap.py
This should not happen (at least for DNS names), but we want to collect them when it happens anyway.
=> XML/Nmap: allow `_` in hostnames

ivre/xmlnmap.py, tests/tests.py
=> XML/Nmap: discard `hostnames` tags outside `host`, fixes GH#1017

ivre/active/data.py
The `http-app` script had an invalid structure that caused the second bug reported in #1020 (and would probably cause other bugs too).
=> Active: fix SharePoint detection

zeek/ivre/passiverecon/__load__.zeek
We may have valid JA3 values even if ssl_established never happens
=> Passive: compute JA3 values as soon as possible

ivre/config.py, ivre/nmapopt.py
I implemented, the --top-ports option for nmap in the nmapopt.py file, added some logical checks against the -p option.
to use it, just add in the variable NMAP_SCAN_TEMPLATES of your ivre config file the option "top_ports" as below
```bash
NMAP_SCAN_TEMPLATES = {
"cyslab": {
"nmap": "nmap",
"pings": "n",
"scans": "V",
"osdetect": False,
"traceroute": False,
"verbosity": 0,
"top_ports": "100",
"ports": "",
"host_timeout": "15m",  # default value: None
"script_timeout": "2m",  # default value: None
"scripts_categories": ['default',], # 'discovery',
}
}
```
the command below should produce the following result : 
```bash
$ ivre runscans --network 192.168.1.0/24 --nmap-template cyslab --output CommandLine
nmap -Pn -sC -sV --top-ports 100 --host-timeout 15m --script-timeout 2m
```
Fixes …
=> Adding nmap --top-ports option in nmapopt.py

ivre/utils.py
There is a small typo in ivre/utils.py.
Should read `protocols` rather than `protcols`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, protcols -> protocols

ivre/active/data.py, ivre/view.py, zeek/ivre/passiverecon/__load__.zeek
For honeypots, it seems interesting to log `DNS` requests issued by scans.
For that, this PR adds an event handler in the script `passiverecon` for zeek. It creates log entries for any `DNS` request to a honeypot address like the following:
```
16097XXXXX.XXXXXX       CAUtCH3aQK42vpZsa       X.X.X.X  -       PassiveRecon::DNS_HONEYPOT_QUERY        53-A-C_INTERNET testip.internet-census.org
```
where `X.X.X.X` is the source `IP` of the `DNS` request.
Once in `ivre`, this allows to query information about `DNS` scans:
```
$ ivre ipinfo X.X.X.X
WARNING:ivre:Cannot find Maxmind database files
DNS_HONEYPOT_QUERY 53-A-C_INTERNET testip.internet-census.org (1 time) 2021-01-04 XX:XX:XX - 2021-01-04 XX:XX:XX
```
This PR also adds these entries in ivre view (using `ivre db2view`).
=> Add DNS queries towards honeypots in Ivre

ivre/web/utils.py
This will make old (Python 2) settings working out of the box
=> Web: accept config.WEB_SECRET as str or bytes

docker/base/Dockerfile
The (Debian) package python3-openssl was missing. Reported by @AxilleasMoukoulis on [gitter](https://gitter.im/cea-sec/ivre)
=> Fix docker base image

ivre/view.py
Rationale: using `lastseen` from the passive record as both `starttime` and `endtime` in the view record) might be surprising, **but** it makes sense when you think about it: it avoids having a scan record with exceptionally long "scan durations".
=> Passive to view: use lastseen as both start and end time

ivre/db/__init__.py, tests/tests.py
This PR also comes with a workaround for #1213. A limited set of tests are skipped with Python 3.9.8.
=> Passive: fix DNS_BLACKLIST updates

.github/actions/install/install.sh, ivre/utils.py, tests/tests.py
This is another fix for #1216.
We have to decide whether pyOpenSSL should be mandatory but in the meantime, let's at least do this!
=> Fix crash when pyOpenSSL is not installed

ivre/passive.py, ivre/view.py, zeek/ivre/passiverecon/__load__.zeek
This adds the detection of STUN requests over UDP based on two regex : 
**Note**: it requires to enable inspection for every incomping UDP packet with a payload ; maybe this is not something we want because of overhead?
```
redef udp_content_deliver_all_orig = T;
```
A compromise could be to enable only for known STUN ports (*e.g.*, 3478).
=> Add STUN to zeek passiverecon script

web/static/ivre/ivre.css
Reverts ivre/ivre#1401
My mistake, I had not tested that with Chrome / Chromium and the result is clearly less good than the previous one.
Sorry @psyray, I hope we'll find another way to fix / handle #1398.
=> Revert "WebUI - Prevent content to be hidden in preview mode"

ivre/db/__init__.py, ivre/db/document.py, ivre/db/mongo.py
About DocumentDB: https://aws.amazon.com/documentdb/
As far as IVRE is concerned, it is just an API similar to MongoDB, with some functionalities missing:
* long index names unsupported (having shorter index names cannot hurt anyway, so those names are set in the MongoDB instance)
* no full text searches (AWS workaround seems to duplicate & sync data to an Elasticsearch instance...)
No CI tests for now.
=> DB: support Amazon DocumentDB

docker/client/Dockerfile
After #1416, Nmap is installed under `/usr`, not `/usr/local`. The Nmap scripts & patches provided with IVRE are not currently correctly installed, which caused the issue reported by @jallphin.
Fixes #1439.
=> Docker/client: fix Nmap scripts install & patches

ivre/zgrabout.py
The current script fails at L413 if, for some reason, the variable `banner` is never set by the previous block. When doing `scan2db`, this bug leads to the result not being imported.
=> Fix bug in zgrabout.py

.github/workflows/mongodb.yml, .github/workflows/tinydb.yml, ivre/tools/version.py, ivre/view.py
MongoDB & TinyDB backends are now tested with all supported Python versions.
Reported by @cybermyber on Gitter.
=> Fix IVRE w/ Python 3.9 (at least)

web/static/templates/view-hosts.html, web/static/templates/view-ports-only.html, web/static/templates/view-screenshots-only.html, web/static/templates/view-scripts-only.html, web/static/templates/view-services-only.html, web/static/templates/view-vulnerabilities-only.html
Before that fix, screenshots would only be displayed when a `service_name` field existed for the port.
=> fix(webui): display screenshots when they exist

docker/client/Dockerfile, patches/nmap/scripts/rdp-screenshot.nse, patches/nmap/scripts/vnc-screenshot.nse
=> Nmap scripts: add RDP screenshot using scrying

docker/web/nginx-default-site
Cookies may sometimes be large and contribute to exceed the `buffer-size` accepted by UWSGI (4096 bytes by default). Since neither `Cookie` or `User-Agent` are used in the Python application, this PR prevents them from being sent by the Nginx proxy.
If you are using IVRE behind CloudFlare for example, this may help!
=> docker/web: limit the headers sent to UWSGI container

ivre/db/__init__.py, ivre/db/sql/sqlite.py, ivre/db/tiny.py, ivre/tools/db2view.py, ivre/tools/runscans.py, tests/tests.py
For now, this is only useful for TinyDB.
This reverts #1602 that was a short-term "solution".
=> CLI/db2view: do not use parallel insert on file-backed DBs

zeek/ivre/passiverecon/ja3.zeek
This will only work for Zeek >= 6.1
----
📚 Documentation preview 📚: https://ivre--1638.org.readthedocs.build/en/1638/
=> Zeek/JA4: fix QUIC protocol detection

zeek/ivre/passiverecon/ja3.zeek
Bug spotted using capture from the JA4 project: [chrome-cloudflare-quic-with-secrets.pcapng](https://github.com/FoxIO-LLC/ja4/blob/977da74d8cf3ac66684bb5d2a92db2f82fc2f4b9/pcap/chrome-cloudflare-quic-with-secrets.pcapng).
----
📚 Documentation preview 📚: https://ivre--1639.org.readthedocs.build/en/1639/
=> Zeek/JA4: do not use version from extension if it's in grease

zeek/ivre/passiverecon/ja3.zeek
As explained by @lrstewart in FoxIO-LLC/ja4#146, JA4 [technical details](https://github.com/FoxIO-LLC/ja4/blob/main/technical_details/JA4.md#extension-hash) mention that:
> If there are no signature algorithms in the hello packet, then the string ends without an underscore and is hashed.
This is part of #1637.
----
📚 Documentation preview 📚: https://ivre--1640.org.readthedocs.build/en/1640/
=> Zeek/JA4: fix ja4_c with no signature algorithms

ivre/analyzer/ja3.py
As explained by @lrstewart in FoxIO-LLC/ja4#146, JA4 [technical details](https://github.com/FoxIO-LLC/ja4/blob/main/technical_details/JA4.md#extension-hash) mention that:
> If there are no signature algorithms in the hello packet, then the string ends without an underscore and is hashed.
This is part of #1637. This is the equivalent of #1640 (which is for Zeek) for Python code for Nmap banner parsing.
----
📚 Documentation preview 📚: https://ivre--1641.org.readthedocs.build/en/1641/
=> Nmap/JA4: fix ja4_c with no signature algorithms

.github/workflows/postgres.yml
This commit replaces unmaintained `harmon758/postgresql-action` action with built-in `services` to pop a PSQL container for testing purposes. As a bonus, it also brings container healthcheck to make sure we wait for database to be ready before proceeding to tests.
Taken from: https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers
----
📚 Documentation preview 📚: https://ivre--1664.org.readthedocs.build/en/1664/
=> refactor(ci): replace unmaintained PSQL action with built-in `services` setup

docker/client/Dockerfile
Add zeek commands located in /opt/zeek/bin to default shell path
----
📚 Documentation preview 📚: https://ivre--1667.org.readthedocs.build/en/1667/
=> Add zeek command to default shell path

ivre/config.py, setup.py
Hello,
This PR to fix `ivre getwebdata` command:
- update  "iso3166.csv" URL from "https://dev.maxmind.com/csv-files/codes/iso3166.csv" to "https://dev.maxmind.com/static/csv/codes/iso3166.csv"
- Embedded "censys_scanners.txt", "ssigouvfr_scanners.txt" and "ukncsc_scanners.txt" form https://github.com/ivre/ivre/pull/1620 into ivre python package
----
📚 Documentation preview 📚: https://ivre--1668.org.readthedocs.build/en/1668/
=> Fix getwebdata downloads

setup.cfg
Towards https://github.com/ivre/ivre/issues/1678.
This commit removes `metadata` and `sdist` sections in `setup.cfg`:
- `metadata` section can be removed as README.md is already used in long_description argument in setup.py.
- `sdist` section can also be removed: `formats=gztar` entry can be removed as this is already the default value. I'm not sure why `owner=root` and `group=root` are needed, it has been added in f7a4002, it can probably be removed.
`python setup.py sdist` on master and on this branch produces the same sdist.
----
📚 Documentation preview 📚: https://ivre--1679.org.readthedocs.build/en/1679/
=> chore(setup.cfg): remove unneeded `metadata` and `sdist` sections

.github/workflows/elastic.yml, .github/workflows/linting.yml, .github/workflows/maxmind.yml, .github/workflows/mongodb.yml, .github/workflows/postgres.yml, .github/workflows/sqlite.yml, .github/workflows/tinydb.yml
It's possible to make it so that CI jobs of a PR are automatically killed when a new commit is pushed to that PR.
This is very useful: if you see jobs starting to fail and you push a fix, you don't have to wait for the previous failing CI build to finish.
See https://github.com/secdev/scapy/pull/4648
=> Auto-kill CI in Pull Requests on new commits

ivre/active/data.py, ivre/activecli.py, ivre/db/__init__.py, ivre/tags/__init__.py, ivre/tools/__init__.py, ivre/utils.py
For httpx, use -tls-grab to add tlsx data.
For tlsx, this patch uses cert data when the raw cert is not included (-cert option)
=> Active: enhance X509 cert support from httpx & tlsx
