ivre/ivre

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/keys.py
- ivre/xmlnmap.py
This fixes #2. Thanks to Camille 'Kamoul0x' Mougey for reporting this.
> Use @staticmethod where appropriate

- ivre/db/mongo.py
Only for non-bulk upserts for now, because of a [MongoDB limitation](http://stackoverflow.com/a/27912334/3223422).
> Add query `.hint()`s for passive data upserts

- MANIFEST
- ivre/db/mongo.py
- setup.py
- web/cgi-bin/scanjson.py
- web/static/help.js
- web/static/index.html
- web/static/ivre.css
- web/static/ivre.js
- web/static/templates/menu.html
- web/static/templates/view-screenshots-only.html
This adds support for screenshots (MongoDB, Web UI) taken with external tools.
> Support for screenshots

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/keys.py
- tests/tests.py
- web/cgi-bin/scanjson.py
This creates a much more "Pythonic" API to look for script results.
> Refactor (Nmap) scripts lookups

- doc/DOCKER.md
This is tested on centos7 host.
> doc: update DOCKER doc for people using selinux enforced

- web/cgi-bin/scanjson.py
> scanjson.py: forgotten line feed

- .travis.yml
- README.md
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/utils.py
- ivre/xmlnmap.py
- requirements.txt
- tests/tests.py
This also fixes the way tests are done.
> Add Travis CI framework

- doc/WEBUI.md
- ivre/db/mongo.py
- web/dokuwiki/doc/webui.txt
- web/static/ivre.js
> Add top ports for a given service

- doc/WEBUI.md
- ivre/db/mongo.py
- ivre/xmlnmap.py
- web/cgi-bin/scanjson.py
- web/dokuwiki/doc/webui.txt
- web/static/help.js
- web/static/ivre.js
- web/static/templates/view-cpes-only.html
- web/static/templates/view-hosts.html
This follows PR #31 and enables CPE filtering in the web ui. Works very well with display:cpe from PR #32.
@p-l-, does the filter syntax seem reasonable to you?
(*Note: the scancli part has not been done yet.*)
> WebUI/db: added a CPE filter

- doc/WEBUI.md
- ivre/db/mongo.py
- web/dokuwiki/doc/webui.txt
- web/static/ivre.js
This completes CPE support (after #31, #32 & #33) by adding CPE top values. See documentation.
> Add topvalues for CPEs (DB/Mongo & WebUI)

- bin/nmap2db
- bin/scancli
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/xmlnmap.py
> nmap2db / DB/MongoDB: introduce --merge option

- doc/README.md
- ivre/config.py
- ivre/db/mongo.py
- web/cgi-bin/scanjson.py
- web/dokuwiki/doc/readme.txt
- web/static/help.js
- web/static/ivre.js
> Support for OCR in screenshot

- bin/scancli
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/xmlnmap.py
- tests/tests.py
This PR
* introduces schema versioning
* introduces a new nested document `openports` in Nmap host documents
* fixes a bug in `nmap2db --merge`
> Schema versioning

- MANIFEST
- ivre/db/__init__.py
- ivre/db/mongo.py
- setup.py
- web/cgi-bin/scanjson.py
- web/static/index.html
- web/static/ivre/controllers.js
- web/static/ivre/ivre.css
- web/static/templates/messages.html
This PR adds support for messages in the Web interface (notice, warning, etc.). `alert()` calls have been updated to use `add_message()`.
A new method has been added to check for schema version mismatches, and new messages have been added in the Web interface when a schema version mismatch is detected (fixes #61).
> WebUI/DB: warning messages

- ivre/db/mongo.py
- ivre/xmlnmap.py
This is needed by #76, but is not enough since "service" tags meaning differ between Nmap and Masscan.
> First steps to accept masscan results

- doc/DOCKER.md
- docker/client/Dockerfile
- web/dokuwiki/doc/docker.txt
> Docker/client: run as root instead of unprivileged user

- setup.py
Reverts cea-sec/ivre#92 (sorry for the unwanted merge)
> Revert "setup.py now uses setuptools instead of distutils"

- ivre/db/mongo.py
- ivre/xmlnmap.py
The current value is now a constant value from `ivre.xmlnmap`.
> XMLNmap: Fix schema_version value

- tests/tests.py
Since @xavier-martin is too lazy for that…
> Tests: add tests for PR #106

- ivre/xmlnmap.py
> Fix Unix file name parsing in ftp-anon output

- bin/scancli
- doc/WEBUI.md
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/webutils.py
- ivre/xmlnmap.py
- web/dokuwiki/doc/webui.txt
- web/static/help.js
- web/static/ivre/controllers.js
- web/static/ivre/graph.js
- web/static/ivre/ivre.js
- web/static/ivre/params.js
- web/static/templates/view-hosts.html
- web/static/templates/view-screenshots-only.html
- web/static/templates/view-scripts-only.html
Fixes #117.
This makes some queries much easier (see PR content).
> Mix host & port scripts

- ivre/db/__init__.py
- ivre/db/mongo.py
- web/cgi-bin/scanjson.py
> Handle MongoDB indexes w/ schema migration

- ivre/db/mongo.py
- web/static/help.js
> DB/Mongo & WebUI: provide script-specific top values for file.*

- MANIFEST
- doc/FAST-INSTALL-AND-FIRST-RUN.md
- doc/INSTALL.md
- docker/web-apache/Dockerfile
- docker/web/nginx-default-site
- ivre/config.py
- ivre/db/mongo.py
- ivre/webutils.py
- ivre/xmlnmap.py
- setup.py
- tests/tests.py
- web/cgi-bin/scanjson.py
- web/cgi-bin/scanupload.py
- web/dokuwiki/doc/fast-install-and-first-run.txt
- web/dokuwiki/doc/install.txt
- web/static/config-sample.js
- web/static/ivre/controllers.js
- web/static/ivre/ivre.js
- web/static/templates/menu.html
- web/static/upload.html
This PR makes it possible to upload scan results to the database using the Web interface.
This feature is not enabled by default.
> Results upload from Web UI

- agent/agent
- bin/runscans
- doc/AGENT.md
- ivre/config.py
- ivre/nmapopt.py
- ivre/target.py
- web/dokuwiki/doc/agent.txt
Templates are stored in the configuration but it should be easy to create a DB backend for that, if found useful.
> Add scan templates

- doc/INSTALL.md
- doc/README.md
- docker/client/Dockerfile
- docker/client/http-screenshot.nse
- docker/client/screenshot.js
- ivre/db/mongo.py
- ivre/utils.py
- ivre/xmlnmap.py
- web/dokuwiki/doc/install.txt
- web/dokuwiki/doc/readme.txt
This PR adds
- an http-screenshot PhantomJS-based Nmap script (`ivre/client` Docker image)
- a PIL-based function to trim screenshots
> Improve screenshots handling

- web/static/ivre/content.js
- web/static/ivre/utils.js
- web/static/report.html
- web/static/templates/menu.html
This includes and hence fixes #150.
> HTML export

- bin/scancli
TODO:
- render CPE
- fix too short variable names
- use saxutils.* instead of .replace() to escape strings properly
> scancli: improve XML output

- doc/WEBUI.md
- ivre/db/mongo.py
- ivre/webutils.py
- web/dokuwiki/doc/webui.txt
- web/static/ivre/content.js
- web/static/ivre/graph.js
After PR #153, complete support for labels. @xavier-martin, what do you think?
> Complete label implementation

- bin/analysercli
- ivre/analyser.py
- ivre/cliutils.py
- setup.py
Implement a clustering and anomaly-detection CLI tool.
> Analyser integration

- web/static/ivre/controllers.js
- web/static/ivre/params.js
- web/static/ivre/utils.js
- web/static/templates/filters.html
- web/static/templates/menu.html
> WebUI: Fix cross-brower differences (Firefox 41+ != Chromium)

- doc/FAST-INSTALL-AND-FIRST-RUN.md
- web/dokuwiki/doc/fast-install-and-first-run.txt
This has been reported and fixed by @fjavierc. Thanks!
> Doc: fix missing package in install procedure

- docker/client/http-screenshot.nse
> Docker/client: http-screenshot script can now use a (v)host name

- ivre/webutils.py
- tests/tests.py
- web/cgi-bin/scanjson.py
- web/static/ivre/controllers.js
- web/static/templates/messages.html
This might help to debug issues (such as #182).
> Fix Web messages

- ivre/db/mongo.py
- web/cgi-bin/scanjson.py
Related in a sense to #192, but independent.
> DB/Mongo/Nmap: add .diff_categories() to compare scan results

- setup.py
> Setup: handle CGI files shebang lines

- web/static/ivre/controllers.js
> WebUI: fix navigation buttons (first/previous/next/last)

- ivre/db/mongo.py
- ivre/nmapout.py
- ivre/tools/scancli.py
- ivre/utils.py
- ivre/xmlnmap.py
- web/static/ivre/ivre.js
- web/static/templates/view-hosts.html
- web/static/templates/view-screenshots-only.html
- web/static/templates/view-scripts-only.html
- Use the magic value -1 instead of "host" for "port" in the fake port entry used to store host scripts.
- Change the structure of the values of "extraports" from `[totalcount, {"state": count}]` to `{"total": totalcount, "state": count}`.
> Schema update for extraports + fake port entry for host scripts

- ivre/geoiputils.py
- ivre/target.py
- ivre/tools/runscans.py
To scan "Picardie" region, use `ivre runscans --region FR B6`.
Greats to @carolineLe! Happy birthday!
> Add --region as target selector (ivre runscans*)

- ivre/db/mongo.py
- ivre/xmlnmap.py
This PR fixes two crashes that occur within specific conditions.
> Fix corner case crashes

- ivre/tools/scancli.py
- ivre/webutils.py
- tests/tests.py
- web/cgi-bin/scanjson.py
- web/static/ivre/content.js
- web/static/ivre/controllers.js
- web/static/templates/menu.html
This PR adds JSON export capability to the Web interface.
> JSON export

- doc/DOCKER.md
- doc/FAST-INSTALL-AND-FIRST-RUN.md
- doc/INSTALL.md
- ivre/tools/ipdata.py
- web/dokuwiki/doc/docker.txt
- web/dokuwiki/doc/fast-install-and-first-run.txt
- web/dokuwiki/doc/install.txt
Simple fix for updating GeoIP informations on already nmap-scanned hosts.
> Added GeoIP infos update on Nmap DB when updating IP data

- ivre/tools/scancli.py
- web/cgi-bin/scanjson.py
- web/static/ivre/controllers.js
This PR brings some fixes after #208.
> Fixes for JSON export

- doc/INSTALL.md
- ivre/tools/runscans.py
I changed the runscans help message regarding stack and heap size.
Also modified the documentation to include the screenshots NSE script.
> Documentation changes

- doc/FLOW.md
Little change in documentation
> Use -w in argus option to write file

- web/static/config-sample.js
- web/static/flow.html
- web/static/ivre/content.js
- web/static/ivre/flow.css
- web/static/ivre/flow/controllers.js
> WebUI/flow: add a timeline

- web/static/flow.html
- web/static/ivre/flow/controllers.js
> WebUI/Flow: make time slots count UI-configurable

- ivre/parser/argus.py
- ivre/parser/netflow.py
> Fix Python 2.6 compatibility

- web/static/flow.html
- web/static/ivre/flow/controllers.js
A bit of refactoring, too.
Ready to merge, although one known bug remains (see FIXME in the diff).
> WebUI/Flow: Play timeline button + highlight flows when hovering timeline

- web/static/ivre/flow/controllers.js
> WebUI/Flow: fix color opacity bug

- ivre/db/neo4j.py
- ivre/tools/flowcli.py
- web/cgi-bin/flowjson.py
- web/static/flow.html
- web/static/ivre/flow/controllers.js
Comments requested on the feature before merge.
> Flow: "orderby" parameter (API + WebUI + CLI)

- README.md
- doc/FLOW.md
- doc/README.md
- doc/WEBUI.md
- ivre/db/neo4j.py
- ivre/tools/flowcli.py
- web/dokuwiki/doc/flow.txt
- web/dokuwiki/doc/readme.txt
- web/dokuwiki/doc/webui.txt
> Flow: syntax for querying arrays (UI + CLI + API)

- ivre/db/mongo.py
- ivre/utils.py
- ivre/xmlnmap.py
- web/static/ivre/graph.js
This PR brings some improvements useful for wide scans:
- support for some AS with missing names in GeoIP database
- support for HTTP Server header from masscan reports
- support for top versions for a particular service or product.
> Improvements for wide scans

- nmap_scripts/rtsp-screenshot.nse
Test if file exists before write "Saved to .."
> Nmap/scripts: fix rtsp-screenshot.nse

- ivre/xmlnmap.py
> XML/Nmap: remove warning for out-of-host script tags

- ivre/utils.py
- tests/results-public-samples
- tests/tests.py
See new test case for an example.
> Nmap: fix specific --country searches

- bin/ivre
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/db/neo4j.py
- ivre/db/postgres.py
- ivre/geoiputils.py
- ivre/passive.py
- ivre/tools/bro2db.py
- ivre/tools/flow2db.py
- ivre/tools/flowcli.py
- ivre/tools/getmoduli.py
- ivre/tools/iphost.py
- ivre/tools/runscansagent.py
- ivre/tools/runscansagentdb.py
- ivre/tools/scan2db.py
- ivre/utils.py
- ivre/webutils.py
- ivre/xmlnmap.py
- tests/tests.py
- web/cgi-bin/flowjson.py
- web/cgi-bin/jsconfig.py
- web/cgi-bin/scanjson.py
- web/cgi-bin/scanupload.py
> Use Python logging module

- ivre/db/mongo.py
> DB/Mongo: fix typo

- docker/base-local/Dockerfile
- docker/base/Dockerfile
- docker/client/Dockerfile
- docker/db/Dockerfile
> Docker: install python future module

- .travis.yml
- .travis/ivre.conf
- ivre/config.py
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/geoiputils.py
- ivre/tools/ipdata.py
- ivre/utils.py
- tests/results-public-samples
- tests/tests.py
This fixes #388 and much more (particularly with Python 3). New tests have been added.
> Multiple fixes in ipdata

- web/static/ivre/controllers.js
- web/static/templates/progressbar.html
> WebUI: use limit (or config.WEB_LIMIT) in forward/back buttons

- bash_completion/ivre
- docker/base/Dockerfile
- docker/client/Dockerfile
- docker/db/Dockerfile
- docker/web/Dockerfile
> Multiple Docker images fixes

- ivre/db/postgres.py
- ivre/tools/passiverecon2db.py
- ivre/tools/passivereconworker.py
- tests/tests.py
This PR uses the p0f2db / passiverecon2db / pasivereconworker commands to insert data for passive tests, and fixes some issues raised by those new tests.
> [2&3] fix passive framework

- docker/client/Dockerfile
This should (really) fix #390 (for ivre/client).
> [docker] Use bro from debian packages

- MANIFEST
- doc/INSTALL.md
- ivre/__init__.py
- web/dokuwiki/doc/install.txt
> Mention the AUR package in the documentation

- .travis.yml
- .travis/ivre.conf
- ivre/agent.py
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/mathutils.py
- ivre/scanengine.py
- ivre/target.py
- ivre/tools/runscans.py
- ivre/tools/runscansagent.py
- tests/tests.py
Fixes #396 (commit 72e0763).
Fixes #270 (commit cc2b094).
Multiple other fixes, including Python 2.6 and 3 compatibility.
> CLI: tests & fixes ivre runscans*

- ivre/xmlnmap.py
- tests/tests.py
> XML Nmap: script table was not reset when script was ignored

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/tools/runscansagentdb.py
- tests/tests.py
> Fixes & workarounds for #403

- .travis/ivre.conf
- ivre/agent.py
- ivre/scanengine.py
- tests/tests.py
This will only work with `ivre runscansagent` and **not** with `ivre runscansagentdb`.
> Handle data (screenshots) in the agent

- .travis.yml
- ivre/utils.py
- ivre/xmlnmap.py
- tests/results-public-samples
- tests/tests.py
Fixes #418 (Python 2 only) and another bug (Python 3 only).
> Fix Nmap probes decoding

- ivre/db/postgres.py
- ivre/tools/iphost.py
- tests/results-public-samples
- tests/tests.py
> Use convert_ip() from ivre.db.db.passive

- ivre/parser/__init__.py
- ivre/parser/airodump.py
- ivre/tools/airodump2db.py
> Fix ivre airodump2db

- ivre/parser/argus.py
- ivre/tools/arp2db.py
> Fix two flow commands

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/db/postgres.py
- ivre/xmlnmap.py
- tests/results-public-samples
- tests/tests.py
- web/cgi-bin/scanjson.py
This fixes some issues related to locations handling (and some issues discovered while fixing them).
> Fix locations handling

- ivre/db/postgres.py
- ivre/tools/ipinfo.py
- tests/tests.py
> postgresql: fix tailf[new] not sorting results correctly.

- ivre/passive.py
- tests/tests.py
Fix for 37b3cb527028cf69244ebdf6977caa2ee2e9c758
> Passive: fix for 37b3cb527028cf69244ebdf6977caa2ee2e9c758

- ivre/db/__init__.py
- ivre/db/postgres.py
- ivre/tools/scancli.py
- ivre/xmlnmap.py
Test will be implemented later.
> DB: fix binary data handling

- tests/tests.py
> Tests: fix passive

- ivre/passive.py
The patterns are replaced with fixed content to avoid record duplication.
> Passive/TCP server banners: find variable patterns

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/tools/scancli.py
> DB/Mongo/Nmap: fix locations

- ivre/db/mongo.py
> DB/Mongo: fix coordiantes in MongoDBNmap.store_host()

- ivre/db/maxmind.py
- ivre/geoiputils.py
- ivre/tools/ipdata.py
- tests/tests.py
>  Fix Geoip2-City CSV dumps

- ivre/config.py
- ivre/tools/httpd.py
- web/static/ivre/tooltip.js
>  Web/CLI: completion suggestions are clickable 

- ivre/config.py
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/passive.py
- ivre/tools/p0f2db.py
- ivre/tools/passiverecon2db.py
- ivre/tools/passivereconworker.py
- ivre/xmlnmap.py
- tests/tests.py
Another option, together with `--bulk` (the default) and `--no-bulk`, has been added: `--local-bulk`. This option will (drastically) limit the traffic to the DB.
> DB/passive: add local bulks to limit traffic to DB

- docker/docker-compose.yml
Hello,
I added support for docker-compose as it's a more common way to deploy simple application with docker.
It adds the auto restart of the whole infrastructure and could easily be modified to set some restriction (cpu/disk/mem...)
I commented the "v3" thing just like in the Vagrantfile :)
Thanks
> Add docker compose support

- ivre/db/__init__.py
- ivre/db/maxmind.py
- ivre/db/mongo.py
#573 was actually broken. Works now :)
+ tiny fixes
> DB/Maxmind: make ivre usable without database files (fix)

- ivre/tools/db2view.py
> fix argument parsing issue in db2view

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/db/sql/__init__.py
- ivre/web/utils.py
- tests/results-public-samples
- tests/tests.py
- web/static/ivre/content.js
> Possibility to negate script filter. Fixes #577

- .travis.yml
- .travis/install_maxmind.sh
- .travis/install_mongo.sh
- .travis/install_postgres.sh
- .travis/install_sqlite.sh
- .travis/ivre.conf
- ivre/db/maxmind.py
- ivre/tools/ipdata.py
- ivre/web/app.py
- tests/tests.py
This PR should also remove timeouts in Maxmind tests (around 3 times 30 seconds).
> Web/API: introduce a /ipdata/ route to query ivre.db.db.data

- doc/AGENT.md
- web/dokuwiki/doc/agent.txt
- web/dokuwiki/doc/readme.txt
> Doc: updates after GH#610

- ivre/db/mongo.py
Some errors existed in the migration process, as reported by @ca0s.
Fixes #620.
> DB/Mongo: fix migrate_schema_hosts_10_11()

- MANIFEST
- doc/WEBUI.md
- setup.py
- web/dokuwiki/doc/webui.txt
- web/static/index.html
- web/static/ivre/content.js
- web/static/ivre/controllers.js
- web/static/templates/view-vulnerabilities-only.html
Updated the previous pull request (#633) based on the comments received. Even though it didn't seem necessary, to be on the safe side I added the `vulns !== undefined` check.
> WebUI: Added display vulnerabilities only filter.

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/db/sql/__init__.py
- ivre/passive.py
- ivre/tools/version.py
- ivre/utils.py
- tests/results-public-samples
- tests/tests.py
This PR also includes tiny fixes for passive schema version 1 in MongoDB.
> Passive: fix & test JA3

- doc/FAST-INSTALL-AND-FIRST-RUN.md
- web/dokuwiki/doc/fast-install-and-first-run.txt
> Doc: fix path

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/db/sql/__init__.py
- tests/tests.py
>  Nmap & View: fix & test searchsshkey() 

- ivre/db/sql/__init__.py
to allow to find a dictionary value from an array
> Modify PostgreSQL searchscript

- doc/INSTALL.md
- web/dokuwiki/doc/install.txt
The redirection is incorrect.
I changed the md file and the dokuwiki page.
> Corrected patch command

- ivre/utils.py
- tests/tests.py
Add tests for utils, add IPv6 address types, and fixes ip2bin.
> Enhance utils

- tests/tests.py
> all2datetime now accepts floats, change test

- ivre/db/__init__.py
- ivre/db/mongo.py
This will speed up tools (CLI, Web app) startup and ivre.db import.
> DB: fix MetaDB() and *DB*() init

- web/static/flow.html
- web/static/ivre/flow.css
- web/static/ivre/flow/controllers.js
- web/static/templates/subview-graph-elt-details.html
- Improve default dark move (colors of sidebar, popovers)
- Add light mode option in "Display" parameters (stored in query parameters)
- Add sidebar removal option as "fullscreen"
- Disallow negative skipping
> Improve flow WebUI

- docker/client/Dockerfile
This should be helpful for #704.
> Docker/client: install nfdump, update Nmap

- ivre/db/neo4j.py
- web/static/ivre/flow.css
At the same time, fix a color issue introduced in #705.
> Add src and dst addresses in flow details

- ivre/parser/__init__.py
> Python 2: fix CmdParser (Argus & NetFlow)

- docker/web-apache/Dockerfile
- docker/web/Dockerfile
- docker/web/nginx-default-site
This is a better fix (hopefully) for #725 after #726.
> Docker: fix web images to handle different PHP versions

- ivre/db/neo4j.py
- web/static/ivre/flow.css
- web/static/templates/subview-graph-elt-details.html
* Fix metadata display with MongoDB backend
* Fix timeline display with Neo4j backend
* Convert timestamps in date strings with Neo4j backend
> Improve flow Web UI

- docker/base-local/Dockerfile
- docker/base-pip/Dockerfile
- docker/base/Dockerfile
- docker/db/Dockerfile
> Docker: add missing configuration files in ivre/base* and ivre/db

- .travis.yml
- .travis/install_elastic.sh
- ivre/db/__init__.py
- ivre/db/elastic.py
- ivre/view.py
- requirements-elastic.txt
- tests/tests.py
Add building blocks of ElasticSearch backend, with Travis tests passed.
> Early Elasticsearch backend implementation

- ivre/db/elastic.py
[Travis-CI results](https://travis-ci.org/p-l-/ivre/builds/577417930)
> DB/Elastic/Active: use geo_point mapping for infos.coordinates

- web/static/doc/_sources/usage/web-ui.rst.txt
- web/static/doc/usage/index.html
- web/static/doc/usage/web-ui.html
> Doc: update after #780

- ivre/web/app.py
- web/static/ivre/content.js
- web/static/ivre/controllers.js
- web/static/templates/menu.html
Implements the first suggestion from #791.
> Web: add an export menu entry for IP addresses

- ivre/web/app.py
- web/static/ivre/controllers.js
> Web: fix upload

- docker/docker-compose.yml
> Docker (compose): use ivre/db instead of mongo container

- docker/web/Dockerfile
> Docker/web: do not fail on second start

- .travis.yml
- .travis/install_tinydb.sh
- ivre/activecli.py
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/db/sql/__init__.py
- ivre/db/tiny.py
- ivre/tools/db2view.py
- ivre/tools/ipinfo.py
- ivre/tools/version.py
- requirements-tinydb.txt
- tests/tests.py
Most of the View purpose should also be covered (but not tested yet). We need to add Passive (then test View) and Flow.
>  DB: add TindyDB support for Nmap

- ivre/xmlnmap.py
- web/static/ivre/ivre.js
This is a workaround for a bug that has been reported to the Nmap project: nmap/nmap#1876.
> XML Nmap: handle a bug in ssl-cert results

- ivre/db/__init__.py
`searchja3server` and `searchja3client` are already implemented and tested in passive backend specific classes.
Therefore, this is only an awful copy/paste of the code which handles ja3 options in view.
> Passive: add ja3 options in ipinfo

- tests/tests.py
> Passive: add tests for ja3 options in ipinfo

- ivre/web/utils.py
- web/static/ivre/content.js
> WebUI & WebAPI: support regexp matches in cert.{md5,sha1,sha256} filters

- ivre/tools/scan2db.py
> CLI/scancli: do not exit 0 if at least one error occured

- docker/client/Dockerfile
> Docker/client: upgrade Nmap to 7.80

- ivre/analyzer/ntlm.py
- ivre/passive.py
- ivre/zgrabout.py
- zeek/ivre/passiverecon/__load__.zeek
> Same NTLM info keys for Nmap, Zgrab2 results and passive

- doc/usage/kibana.rst
- web/static/doc/_sources/usage/kibana.rst.txt
- web/static/doc/usage/kibana.html
> fix(doc): forgotten a at end of Kibana

- ivre/config.py
- ivre/utils.py
Performances on python versus native binaries are quite identical, for hash & compression.
This PR removes the use of native binaries
> Use python hash zip

- ivre/active/data.py
> Fix CPE merge (GH#1020)

- ivre/active/data.py
- ivre/view.py
- zeek/ivre/passiverecon/__load__.zeek
This also removes a trailing `/` from CPE values.
> Passive & View: detect SharePoint from Zeek

- .travis.yml
This PR only **removes** tests, can be merged safely.
> Travis-CI: remove more tests (Python 3.4)

- ivre/analyzer/ntlm.py
Bug identified (and fix idea provided) by @Rhaev3n
> Fix NTLMSSP Authenticate message parsing

- zeek/ivre/passiverecon/__load__.zeek
> Passive: NTLM_CLIENT_FLAGS were incorrectly attributed to the server

- ivre/db/mongo.py
This will speed-up timeago-filtered db2view operations.
> DB/Mongo/Passive: the index for lastseen also indexes the address fields

- ivre/db/http.py
- ivre/db/mongo.py
- ivre/web/app.py
- ivre/web/utils.py
- tests/tests.py
This should remove all the limitations of the HTTP backend (for active purposes)
> Enhance HTTP backend

- ivre/db/__init__.py
- ivre/db/http.py
- tests/tests.py
Support DB_DATA implemented using an IVRE HTTP server instance.
> DB/Http: add Data purpose support

- ivre/active/data.py
- ivre/db/__init__.py
- ivre/utils.py
- ivre/zgrabout.py
- tests/tests.py
See https://github.com/projectdiscovery/nuclei
Cc @0xtavian
> Active: (early & limited) support for Nuclei (ProjectDiscovery)

- ivre/db/mongo.py
> DB/Mongo: create new indexes on schema migration

- README.md
> Add Emma Leroy to the contributors

- ivre/analyzer/dns.py
- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/target.py
- ivre/tools/auditdom.py
- ivre/utils.py
- ivre/xmlnmap.py
- tests/tests.py
This PR also adds fixes required by the new Pylint version.
> CLI/auditdom: implement TLS-RPT & DNS NS records checkers

- ivre/db/mongo.py
- ivre/db/sql/__init__.py
- ivre/db/tiny.py
- ivre/tools/airodump2db.py
- ivre/tools/macinfo.py
- tests/tests.py
Fixes #1146.
Data from Airodump now feeds the `passive` database.
> Passive: fix airodump2db

- ivre/db/__init__.py
- ivre/db/mongo.py
This will be useful to add passive data to the demo instance
> DB/Passive: support .searchcategory() using sensor name

- ivre/db/mongo.py
- ivre/db/tiny.py
> Active: enable OS type search

- ivre/db/http.py
> DB/HTTP: support PKCS11 client certificate authentication

- ivre/db/__init__.py
- ivre/tools/airodump2db.py
- ivre/tools/p0f2db.py
- ivre/tools/passiverecon2db.py
> Passive: avoid code duplication for CLI insertion options

- ivre/active/data.py
- ivre/view.py
part of https://github.com/ivre/ivre/pull/1175
This PR:
- a few improvements to how scanners are displayed (now also displays which probe were found to be able to identify false positives, if any)
> Improve how scanners are displayed

- .github/workflows/elastic.yml
- .github/workflows/maxmind.yml
- .github/workflows/mongodb.yml
- .github/workflows/postgres.yml
- .github/workflows/sqlite.yml
- .github/workflows/tinydb.yml
- ivre/web/utils.py
This PR also includes in GitHub actions a debug trick we used to have with Travis CI.
> Web/UI: support IPv6 (net & addr) filters

- ivre/db/__init__.py
Fixes #1203, reported by @itnsec, help provided by @0xtavian.
> scans/Nuclei: support v2.5.3 format

- ivre/db/http.py
> DB/HTTP: support sort

- docker/client/Dockerfile
> Docker/client: install p0f

- ivre/utils.py
> Utils: collect certificates serial numbers, versions and signature algos

- ivre/db/__init__.py
- ivre/db/sql/__init__.py
This prevents some false positives.
> TOR certificates are not self-signed

- ivre/xmlnmap.py
> Fix a crash in schema migration (13 -> 14)

- ivre/db/__init__.py
- ivre/db/elastic.py
- ivre/db/mongo.py
- ivre/db/sql/postgres.py
- ivre/db/tiny.py
- ivre/web/utils.py
- tests/tests.py
> Handle JARM values (top values, Web filter)

- ivre/db/__init__.py
- ivre/tools/ipinfo.py
- ivre/tools/scancli.py
- ivre/tools/view.py
- ivre/utils.py
>  CLI/ipinfo,scancli,view: support --to-db & --from-db options

- ivre/db/__init__.py
- ivre/db/mongo.py
- requirements-mongosrv.txt
- setup.py
> DB/MongoDB: support mongodb+srv URLs

- ivre/db/__init__.py
- ivre/tools/runscans.py
See [projectdiscovery/httpx](https://github.com/projectdiscovery/httpx).
Suggested by @itnsec. Fixes #1261.
> Active: (early & limited) support for httpx (ProjectDiscovery)

- ivre/db/__init__.py
> Active/Nuclei: support new field name "matcher-name" for "matcher_name"

- ivre/utils.py
- tests/tests.py
range2nets() is now a generator
> Utils: support IPv6 in range2nets

- tests/tests.py
See https://www.python.org/dev/peps/pep-0632/
> Drop deprecated distutils.spawn usage

- README.md
- ivre/db/__init__.py
- ivre/db/mongo.py
_Originally reported by @itnsec in https://github.com/ivre/ivre/issues/1282#issuecomment-1013706569_
> Active: fix timestamp format in dnsx results

- ivre/db/__init__.py
_Reported & suggested by @itnsec in https://github.com/ivre/ivre/pull/1284#issuecomment-1014773008_
> DB/Active/dnsz: import fixes

- ivre/db/__init__.py
- ivre/db/elastic.py
- ivre/db/mongo.py
- ivre/db/sql/postgres.py
- ivre/db/tiny.py
- ivre/xmlnmap.py
That's another document schema update :-/
> DB/Active: index JARM values

- ivre/parser/weblog.py
- ivre/tools/__init__.py
- ivre/tools/p0f2db.py
- ivre/tools/passivereconworker.py
- ivre/tools/weblog2db.py
* Produces records `{"recontype": "HTTP_CLIENT_HEADER", "source": "USER-AGENT"}`
* Tiny fixes for passive tools
> CLI/Passive: add weblog2db for Apache / Nginx "combined" log format

- ivre/geoiputils.py
> geoiputils: only download (and extract) new files

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/db/sql/__init__.py
- ivre/utils.py
This PR provides a (limited) support for Shodan exported results. This might be useful to combine (and compare) Shodan results with other scan results (Masscan, Nmap) of your own.
> Scan: early support for Shodan exported results

- ivre/db/mongo.py
- ivre/utils.py
- ivre/xmlnmap.py
- ivre/zgrabout.py
Fixes #1326. Needs patch from zmap/zgrab2#347 applied, which is currently not in zgrab2 master.
> Zgrab2: support raw HTTP headers

- ivre/db/__init__.py
Template added in projectdiscovery/nuclei-templates#4239
> active/Nuclei: add http-app pseudo-script & CPE for SharePoint

- ivre/db/__init__.py
- ivre/view.py
- ivre/xmlnmap.py
- ivre/zgrabout.py
See https://github.com/zhzyker/dismap
> active: support dismap

- ivre/db/__init__.py
This produces `service_{product,version}` fields and `http-{server-header,headers,content,title,ls}` scripts.
> Active/Dismap: handle HTTP headers & body

- ivre/db/__init__.py
- tests/tests.py
> CLI: support --no-timeago{,new}

- ivre/db/mongo.py
- ivre/db/sql/__init__.py
- ivre/db/tiny.py
- ivre/keys.py
- ivre/passive.py
- ivre/tools/ipinfo.py
- ivre/types/__init__.py
- ivre/view.py
- tests/tests.py
Fixes #1370
**Passive document schema update!**
> DB/Passive: improve .searchsshkey() API

- docker/client/Dockerfile
- patches/nmap/scripts/http-screenshot.nse
- patches/nmap/scripts/mainframe-screenshot.nse
> Nmap/http-screenshot: switch to phantomjs-2.1.1, support IPv6 addresses

- web/static/ivre/ivre.css
> WebUI - Prevent content to be hidden in preview mode

- ivre/active/data.py
> View: "merge" extraports field when possible

- ivre/db/mongo.py
This is useful for e.g., Amazon DocumentDB connection URLs
> DB/Mongo: fix connection parameters

- ivre/db/__init__.py
- ivre/db/mongo.py
- ivre/view.py
> DB/Mongo/db2view: attempt to retry on cursor timeout

- ivre/zgrabout.py
This bugs leads to the result file not being imported.
> Fix bug when 'path' is not in the 'request' dictionary of the json file

- ivre/active/data.py
- ivre/tools/getwebdata.py
<https://www.ncsc.gov.uk/information/ncsc-scanning-information>
> Active: tag scanners from UK NCSC

- ivre/db/mongo.py
This was reported by @kaon1 in a [comment](https://github.com/ivre/ivre/discussions/1463#discussioncomment-4615775) in #1463
> DB/Mongo: fix .diff_categories() addr values

- zeek/ivre/passiverecon/ja3.zeek
Fix provided by @benjeems. See salesforce/ja3#87
> Zeek: fix for 5.2

- ivre/utils.py
> Passive: file `nmap-payloads` is obsolete

- ivre/db/__init__.py
> ZDNS: handle answers with missing fields

- patches/nmap/pr-2142.patch
- patches/nmap/pr-2229.patch
- setup.py
This adds two unmerged PRs from the Nmap project as patches for our Nmap installations:
- nmap/nmap#2142
- nmap/nmap#2229
> Patches/Nmap: add two unmerged PRs

- docker/client/Dockerfile
> Docker/client: install argus-client package for flow2db

- ivre/tools/version.py
- requirements-all.txt
- requirements-elastic.txt
- setup.py
Temporary fix (at least for CI) for #1581.
> DB/elastic: lock elasticsearch < 8.9.0

- docker/base/Dockerfile
- docker/client/Dockerfile
> Docker: add ca-certificates to enable HTTPS downloads

- docker/base-local/Dockerfile
> Docker: fix base-local image after GH-1593

- ivre/db/__init__.py
> Active/Dismap: support (new) NDJSON formst

- .github/workflows/linting.yml
- ivre/active/data.py
- ivre/db/__init__.py
- ivre/db/elastic.py
- ivre/db/http.py
- ivre/db/maxmind.py
- ivre/db/mongo.py
- ivre/db/sql/__init__.py
- ivre/db/sql/postgres.py
- ivre/db/sql/sqlite.py
- ivre/db/tiny.py
- ivre/geoiputils.py
- ivre/scanengine.py
- ivre/tools/airodump2db.py
- ivre/tools/flowcli.py
- ivre/tools/passivereconworker.py
- ivre/tools/scan2db.py
- ivre/types/__init__.py
- ivre/web/utils.py
- ivre/xmlnmap.py
- pkg/runchecks
- tests/tests.py
This was inspired by a [message](https://matrix.to/#/!FfISACyptWXzyzxAMb:gitter.im/$SRr0Jy1ZQ7RsU0RUz-7t68VrbBvrpnKRj5VNgKh7m34?via=gitter.im&via=matrix.org) on [gitter](https://app.gitter.im/#/room/#ivre_ivre:gitter.im) from [ExF](https://matrix.to/#/@efilatov1_gitlab:gitter.im).
> Active/httpx: support headers & body reported with `-irr` flag

- ivre/db/__init__.py
- ivre/parser/airodump.py
- ivre/tools/airodump2db.py
- ivre/tools/p0f2db.py
- ivre/tools/passiverecon2db.py
- ivre/tools/scan2db.py
- ivre/tools/weblog2db.py
- ivre/tools/zeek2db.py
- ivre/utils.py
> CLI/passive & flow: allow recursion with -f

- .readthedocs.yaml
----
📚 Documentation preview 📚: https://ivre--1624.org.readthedocs.build/en/1624/
> CI/readthedocs: do not fail on warnings

- ivre/target.py
Fixes #1627 
----
📚 Documentation preview 📚: https://ivre--1629.org.readthedocs.build/en/1629/
> CLI/runscans: fix --nmap-prescan-ports crash

- ivre/passive.py
As explained by @lrstewart in FoxIO-LLC/ja4#146, JA4 [technical details](https://github.com/FoxIO-LLC/ja4/blob/main/technical_details/JA4.md#extension-hash) mention that:
> If there are no signature algorithms in the hello packet, then the string ends without an underscore and is hashed.
This is part of #1637:
- this includes the equivalent of #1640 (which is for Zeek) for Python code for Passive data.
- this also hardens JA4 value parsing which may be useful in case some tools report weird ALPN values for example.
----
📚 Documentation preview 📚: https://ivre--1642.org.readthedocs.build/en/1642/
> Passive/JA4: harden value parsing, fix ja4_c with no signature algorithms

- ivre/passive.py
----
📚 Documentation preview 📚: https://ivre--1643.org.readthedocs.build/en/1643/
> Passive/JA4: store {ja4_a, ja4_b, ja4_c} values

- zeek/ivre/passiverecon/ja3.zeek
See #1637,  FoxIO-LLC/ja4#148 & FoxIO-LLC/ja4@a5c1f85.
----
📚 Documentation preview 📚: https://ivre--1645.org.readthedocs.build/en/1645/
> Zeek/JA4: fix ALPN based on updated spec

- ivre/analyzer/ja3.py
See #1637,  FoxIO-LLC/ja4#148 & FoxIO-LLC/ja4@a5c1f85.
----
📚 Documentation preview 📚: https://ivre--1646.org.readthedocs.build/en/1646/
> Nmap/JA4: fix ALPN based on updated spec

- ivre/active/data.py
- ivre/db/__init__.py
- ivre/db/elastic.py
- ivre/db/mongo.py
- ivre/plugins.py
- ivre/tools/__init__.py
- ivre/tools/version.py
- ivre/view.py
----
📚 Documentation preview 📚: https://ivre--1654.org.readthedocs.build/en/1654/
> Support plugins for DB (base, elastic, mongo)

- ivre/analyzer/ja3.py
- zeek/ivre/passiverecon/ja3.zeek
See #1637, FoxIO-LLC/ja4#148 & FoxIO-LLC/ja4#156.
----
📚 Documentation preview 📚: https://ivre--1655.org.readthedocs.build/en/1655/
> JA4: fix ALPN based on updated spec

- ivre/plugins.py
- ivre/tags/__init__.py
- ivre/tags/active.py
----
📚 Documentation preview 📚: https://ivre--1657.org.readthedocs.build/en/1657/
> Support plugins for Tags (base, active)

- ivre/db/__init__.py
This PR also moved some CLI options to the generic section so that they can be used by both active and passive CLI with the same meaning.
----
📚 Documentation preview 📚: https://ivre--1658.org.readthedocs.build/en/1658/
> CLI: support `--cert <FINGERPRINT>` in active & passive tools 

- ivre/tags/active.py
----
📚 Documentation preview 📚: https://ivre--1660.org.readthedocs.build/en/1660/
> Tags/Active: update generators prototype to include the NmapHost

- ivre/__init__.py
----
📚 Documentation preview 📚: https://ivre--1663.org.readthedocs.build/en/1663/
> version: use both annotated and lightweight tags

- tests/tests.py
----
📚 Documentation preview 📚: https://ivre--1665.org.readthedocs.build/en/1665/
> CI/tests: use .assertAlmostEqual() for tags count

- zeek/ivre/passiverecon/__load__.zeek
- zeek/ivre/passiverecon/bare.zeek
This should fix #1666.
----
📚 Documentation preview 📚: https://ivre--1669.org.readthedocs.build/en/1669/
> Zeek: fix with Zeek >= 7

- ivre/db/__init__.py
- tests/tests.py
----
📚 Documentation preview 📚: https://ivre--1673.org.readthedocs.build/en/1673/
> Active/Nuclei: support DNS "ptr-fingerprint" template

- ivre/analyzer/ja3.py
----
📚 Documentation preview 📚: https://ivre--1675.org.readthedocs.build/en/1675/
> Nmap/{JA3,JA4}: do not crash on Scapy failure

- ivre/active/nmap.py
- ivre/db/__init__.py
----
📚 Documentation preview 📚: https://ivre--1677.org.readthedocs.build/en/1677/
> Active/Nuclei: support SSL & TCP templates

- ivre/db/__init__.py
Add negative tag filter for "ivre view" command
Ex: ivre view --tag '!Reserved address'
----
📚 Documentation preview 📚: https://ivre--1680.org.readthedocs.build/en/1680/
> Update __init__.py - Add Negative tag filter

- ivre/activecli.py
- ivre/tools/view.py
----
📚 Documentation preview 📚: https://ivre--1681.org.readthedocs.build/en/1681/
> CLI/view: add more URLs in --http-urls*

- ivre/db/mongo.py
Just trying to mimic the same pattern as in the Passive DB, where the pre-storing processing is done in a function.
This is what was done in MongoDBPassive:
https://github.com/ivre/ivre/blob/031db515423f12fcd30c1f9867b56bebdcf26c5f/ivre/db/mongo.py#L4781-L4789
> Split store_host on Nmap's ActiveDB

- ivre/db/__init__.py
See https://github.com/fox-it/citrix-netscaler-triage
> feat(active): support Citrix NetScaler Triage
